apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-java-quarkus-chzjwmof
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: nexus-docker-nexus.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/backend-tests-java-quarkus-chzjwmof:github-0413f95b4e83ffdb05f96ea74c5c11a08c742e3d
        name: container-image  
